export const DEFAULT_WORK_START_HOUR = 8;
export const DEFAULT_WORK_START_MINUTES = 0;
export const DEFAULT_WORK_END_HOUR = 20;
export const DEFAULT_WORK_END_MINUTES = 0;
export const DEFAULT_APPOINTMENT_DURATION = 60;

export const DEAFULT_WORK_ON_SATURDAY = false;
export const DEAFULT_WORK_ON_SUNDAY = false;

export const APPOINTMENTS = 'APPOINTMENTS';
export const APPOINTMENTS_DELETED = 'APPOINTMENTS_DELETED';
